// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: overlock/storage/oci_registry.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	types "github.com/web-seven/overlock-api/go/overlock/x/crossplane/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// OCIRegistry
type OCIRegistry struct {
	// id
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// creator
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	// metadata
	Metadata *types.Metadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *RegistrySpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (m *OCIRegistry) Reset()         { *m = OCIRegistry{} }
func (m *OCIRegistry) String() string { return proto.CompactTextString(m) }
func (*OCIRegistry) ProtoMessage()    {}
func (*OCIRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_853bb2175a8de8b8, []int{0}
}
func (m *OCIRegistry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OCIRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OCIRegistry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OCIRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OCIRegistry.Merge(m, src)
}
func (m *OCIRegistry) XXX_Size() int {
	return m.Size()
}
func (m *OCIRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_OCIRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_OCIRegistry proto.InternalMessageInfo

func (m *OCIRegistry) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OCIRegistry) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *OCIRegistry) GetMetadata() *types.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *OCIRegistry) GetSpec() *RegistrySpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

// RegistrySpec
type RegistrySpec struct {
	// url
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// type
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// provider
	Provider string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
}

func (m *RegistrySpec) Reset()         { *m = RegistrySpec{} }
func (m *RegistrySpec) String() string { return proto.CompactTextString(m) }
func (*RegistrySpec) ProtoMessage()    {}
func (*RegistrySpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_853bb2175a8de8b8, []int{1}
}
func (m *RegistrySpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegistrySpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegistrySpec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegistrySpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrySpec.Merge(m, src)
}
func (m *RegistrySpec) XXX_Size() int {
	return m.Size()
}
func (m *RegistrySpec) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrySpec.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrySpec proto.InternalMessageInfo

func (m *RegistrySpec) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RegistrySpec) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RegistrySpec) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func init() {
	proto.RegisterType((*OCIRegistry)(nil), "overlock.storage.OCIRegistry")
	proto.RegisterType((*RegistrySpec)(nil), "overlock.storage.RegistrySpec")
}

func init() {
	proto.RegisterFile("overlock/storage/oci_registry.proto", fileDescriptor_853bb2175a8de8b8)
}

var fileDescriptor_853bb2175a8de8b8 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xb1, 0x4e, 0xeb, 0x30,
	0x14, 0x86, 0xeb, 0x36, 0xba, 0xb7, 0x71, 0x11, 0xaa, 0x3c, 0x59, 0x95, 0xb0, 0xa2, 0xb0, 0x64,
	0x72, 0xa4, 0x30, 0xb1, 0xc2, 0xc4, 0x80, 0x40, 0x66, 0x63, 0x41, 0xc6, 0xb1, 0xaa, 0x88, 0x80,
	0xad, 0x63, 0x53, 0xd1, 0xb7, 0xe0, 0x29, 0x78, 0x16, 0xc6, 0x8e, 0x8c, 0x28, 0x79, 0x11, 0x54,
	0x93, 0x18, 0xc4, 0x76, 0x8e, 0xf5, 0x9d, 0xdf, 0x9f, 0x7e, 0x7c, 0x6c, 0x36, 0x1a, 0x5a, 0xa3,
	0x1e, 0x4a, 0xe7, 0x0d, 0xc8, 0xb5, 0x2e, 0x8d, 0x6a, 0xee, 0x40, 0xaf, 0x1b, 0xe7, 0x61, 0xcb,
	0x2d, 0x18, 0x6f, 0xc8, 0x72, 0x84, 0xf8, 0x00, 0xad, 0xf2, 0x78, 0xa6, 0xc0, 0x38, 0x67, 0x5b,
	0xf9, 0xa4, 0xcb, 0x47, 0xed, 0x65, 0x2d, 0xbd, 0xfc, 0xbe, 0xca, 0xdf, 0x10, 0x5e, 0x5c, 0x9d,
	0x5f, 0x88, 0x21, 0x8b, 0x1c, 0xe2, 0x69, 0x53, 0x53, 0x94, 0xa1, 0x22, 0x11, 0xd3, 0xa6, 0x26,
	0x14, 0xff, 0x57, 0xa0, 0xa5, 0x37, 0x40, 0xa7, 0x19, 0x2a, 0x52, 0x31, 0xae, 0xe4, 0x14, 0xcf,
	0xc7, 0x2c, 0x3a, 0xcb, 0x50, 0xb1, 0xa8, 0x8e, 0x78, 0x54, 0xf8, 0xf9, 0x90, 0x5f, 0x0e, 0x90,
	0x88, 0x38, 0xa9, 0x70, 0xe2, 0xac, 0x56, 0x34, 0x09, 0x67, 0x8c, 0xff, 0x35, 0xe7, 0xa3, 0xce,
	0x8d, 0xd5, 0x4a, 0x04, 0x36, 0xbf, 0xc6, 0x07, 0xbf, 0x5f, 0xc9, 0x12, 0xcf, 0x9e, 0xa1, 0x0d,
	0xa6, 0xa9, 0xd8, 0x8f, 0x84, 0xe0, 0xc4, 0x6f, 0xad, 0x1e, 0x3c, 0xc3, 0x4c, 0x56, 0x78, 0x6e,
	0xc1, 0x6c, 0x9a, 0x5a, 0x43, 0x90, 0x4c, 0x45, 0xdc, 0xcf, 0xaa, 0xf7, 0x8e, 0xa1, 0x5d, 0xc7,
	0xd0, 0x67, 0xc7, 0xd0, 0x6b, 0xcf, 0x26, 0xbb, 0x9e, 0x4d, 0x3e, 0x7a, 0x36, 0xb9, 0xa5, 0xb1,
	0xb8, 0x97, 0xd8, 0xf8, 0x3e, 0xce, 0xdd, 0xff, 0x0b, 0xad, 0x9d, 0x7c, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x16, 0xe3, 0x99, 0x17, 0x92, 0x01, 0x00, 0x00,
}

func (m *OCIRegistry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OCIRegistry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OCIRegistry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Spec != nil {
		{
			size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOciRegistry(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOciRegistry(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintOciRegistry(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintOciRegistry(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RegistrySpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegistrySpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegistrySpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintOciRegistry(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintOciRegistry(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintOciRegistry(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintOciRegistry(dAtA []byte, offset int, v uint64) int {
	offset -= sovOciRegistry(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OCIRegistry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovOciRegistry(uint64(m.Id))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovOciRegistry(uint64(l))
	}
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovOciRegistry(uint64(l))
	}
	if m.Spec != nil {
		l = m.Spec.Size()
		n += 1 + l + sovOciRegistry(uint64(l))
	}
	return n
}

func (m *RegistrySpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovOciRegistry(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovOciRegistry(uint64(l))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovOciRegistry(uint64(l))
	}
	return n
}

func sovOciRegistry(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOciRegistry(x uint64) (n int) {
	return sovOciRegistry(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OCIRegistry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOciRegistry
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OCIRegistry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OCIRegistry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOciRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOciRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOciRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOciRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOciRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOciRegistry
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOciRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &types.Metadata{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOciRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOciRegistry
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOciRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Spec == nil {
				m.Spec = &RegistrySpec{}
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOciRegistry(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOciRegistry
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegistrySpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOciRegistry
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegistrySpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegistrySpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOciRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOciRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOciRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOciRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOciRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOciRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOciRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOciRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOciRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOciRegistry(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOciRegistry
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOciRegistry(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOciRegistry
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOciRegistry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOciRegistry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOciRegistry
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOciRegistry
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOciRegistry
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOciRegistry        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOciRegistry          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOciRegistry = fmt.Errorf("proto: unexpected end of group")
)
